import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { drizzle } from 'drizzle-orm/node-postgres';
import pg from 'pg';
import * as schema from '../../../src/config/db-schema.js';
import type { CanonicalEvent } from '../../../src/contracts/events/canonical-event.js';
import { seedIdentity } from '../../../src/modules/demo/seed-identity.js';
import { createTenantContext } from '../../../src/modules/identity/tenant-context.js';
import { ingestAndProject } from '../../../src/modules/ingestion/pipeline.js';
import { replayTenantProjections } from '../../../src/modules/projection/replay.js';
import { createMigratedTestDatabase, type TestDatabase } from '../helpers/test-db.js';

const SUBJECT_KEY = 'order:cross-rebuild:seller-1';

/**
 * The SAME logical event sequence, described independently of any
 * database-generated id. `event_id`/`source_event_id` are fixed literals (not
 * randomUUID), but `ingest_events.id` — the internal surrogate primary key —
 * is still freshly randomUUID-generated by `acceptEvidence` in EACH separate
 * database. If projection ordering or the replay manifest depended on that
 * surrogate id, the two independent rebuilds below would diverge.
 */
function events(): readonly CanonicalEvent[] {
  const base = (
    id: string,
    eventType: string,
    eventTime: string,
    refs: Record<string, string>,
    amountMinor: bigint,
    sourceEntityVersion: number | null = null,
  ): CanonicalEvent =>
    ({
      event_id: `evt_${id}`,
      tenant_id: 'ten_demo',
      source_system: 'SYNTHETIC_ROUTE',
      source_account_id: null,
      source_event_id: `source_${id}`,
      source_event_type: eventType,
      event_type: eventType,
      schema_version: '1.0',
      event_time: eventTime,
      ingested_at: eventTime,
      source_entity_version: sourceEntityVersion,
      entity_references: refs,
      economic_subject_hint: SUBJECT_KEY,
      amount_minor: amountMinor.toString(),
      currency: 'INR',
      correlation_id: null,
      causation_id: null,
      payload_hash: `sha256:${id.padEnd(64, '0').slice(0, 64)}`,
      raw_payload_ref: `db:ingest_events/${id}`,
      metadata: { environment: 'synthetic' },
      data: {},
    }) as CanonicalEvent;

  return [
    base(
      'capture',
      'PaymentCaptured',
      '2026-08-25T05:00:00Z',
      { payment_id: 'payment_xr' },
      50_000_000n,
    ),
    base(
      'transfer',
      'TransferProcessed',
      '2026-08-25T05:10:00Z',
      { transfer_id: 'transfer_xr', recipient_account_id: 'recipient_xr' },
      45_500_000n,
    ),
    // Genuinely tied on event_time AND source_entity_version (both null) with
    // the ORIGINAL transfer event above is not exercised here (each has a
    // distinct event_time), but the reversal below IS the same class of
    // decision `compareProjectionOrder` must resolve identically in both
    // independent rebuilds via the content-derived tiebreaker.
    base(
      'failed',
      'SyntheticTransferFailed',
      '2026-08-25T05:20:00Z',
      { transfer_id: 'transfer_xr', recipient_account_id: 'recipient_xr' },
      45_500_000n,
    ),
    base(
      'receivable_open',
      'SellerReceivableOpened',
      '2026-08-25T05:30:00Z',
      { receivable_id: 'receivable_xr' },
      45_500_000n,
    ),
    base(
      'receivable_closed',
      'SellerReceivableClosed',
      '2026-08-25T05:40:00Z',
      { receivable_id: 'receivable_xr' },
      45_500_000n,
    ),
    base(
      'receivable_reopen',
      'SellerReceivableOpened',
      '2026-08-25T05:50:00Z',
      { receivable_id: 'receivable_xr' },
      45_500_000n,
    ),
    base(
      'recovery_scheduled',
      'RecoveryScheduled',
      '2026-08-25T06:00:00Z',
      { recovery_id: 'recovery_xr' },
      50_000_000n,
    ),
    base(
      'recovery_suppressed',
      'RecoverySuppressed',
      '2026-08-25T06:10:00Z',
      { recovery_id: 'recovery_xr' },
      50_000_000n,
    ),
  ];
}

async function buildIndependentDatabase(): Promise<{
  testDb: TestDatabase;
  pool: pg.Pool;
  db: ReturnType<typeof drizzle<typeof schema>>;
}> {
  const testDb = await createMigratedTestDatabase();
  const pool = new pg.Pool({ connectionString: testDb.databaseUrl });
  const db = drizzle(pool, { schema });
  await seedIdentity(db);
  const ctx = createTenantContext('ten_demo', 'demo');
  for (const event of events()) {
    const accepted = await ingestAndProject(db, ctx, {
      event,
      rawBytes: JSON.stringify(event),
      signatureStatus: 'verified',
    });
    if (accepted.outcome !== 'accepted') {
      throw new Error(`fixture event ${event.event_id} was not accepted: ${accepted.outcome}`);
    }
  }
  return { testDb, pool, db };
}

describe('replay manifest determinism across independent rebuilds', () => {
  let first: Awaited<ReturnType<typeof buildIndependentDatabase>>;
  let second: Awaited<ReturnType<typeof buildIndependentDatabase>>;

  beforeAll(async () => {
    // Built SEQUENTIALLY, each from its own fresh `createMigratedTestDatabase()`
    // call — two entirely separate Postgres databases, each assigning its own
    // independent random surrogate ids to every row.
    first = await buildIndependentDatabase();
    second = await buildIndependentDatabase();
  });

  afterAll(async () => {
    await first?.pool?.end();
    await first?.testDb?.teardown();
    await second?.pool?.end();
    await second?.testDb?.teardown();
  });

  it('produces byte-identical manifest and shadow-manifest hashes for the same logical events in two fresh databases', async () => {
    const ctx = createTenantContext('ten_demo', 'demo');
    const resultA = await replayTenantProjections(first.db, ctx);
    const resultB = await replayTenantProjections(second.db, ctx);

    expect(resultA.matchesShadow).toBe(true);
    expect(resultB.matchesShadow).toBe(true);
    expect(resultA.eventCount).toBe(resultB.eventCount);

    // The actual proof: two INDEPENDENTLY REBUILT databases (fresh CREATE
    // DATABASE, fresh migration run, fresh randomUUID surrogate keys for
    // every ingest_events/entity_revisions row) converge on the exact same
    // manifest hash for the same logical event content. If ordering or the
    // manifest depended on a random ingestion-time id, this would fail with
    // overwhelming probability every run.
    expect(resultB.manifestHash).toBe(resultA.manifestHash);
    expect(resultB.shadowManifestHash).toBe(resultA.shadowManifestHash);
  });
});
